# Generated by Django 6.0.1 on 2026-01-22 19:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('chair', 'Chair'), ('bed', 'Bed'), ('table', 'Table'), ('sofa', 'Sofa'), ('cabinet', 'Cabinet'), ('shelf', 'Shelf'), ('stool', 'Stool'), ('bench', 'Bench')], max_length=20)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('description', models.TextField(blank=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('production_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Work Station',
                'verbose_name_plural': 'Work Stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabourTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('cutting', 'Cutting Cover'), ('laying', 'Laying Cover'), ('finishing', 'Finishing'), ('skeleton', 'Skeleton Building'), ('assembly', 'Assembly'), ('upholstery', 'Upholstery'), ('sanding', 'Sanding'), ('painting', 'Painting'), ('polishing', 'Polishing'), ('packaging', 'Packaging')], max_length=20)),
                ('task_name', models.CharField(blank=True, max_length=100)),
                ('labour_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_hours', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('description', models.TextField()),
                ('sequence', models.IntegerField(default=0, help_text='Order in which this task should be performed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_tasks', to='production.product')),
            ],
            options={
                'verbose_name': 'Labour Task',
                'verbose_name_plural': 'Labour Tasks',
                'ordering': ['sequence', 'task_type'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Production Order Number')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='pending', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1)),
                ('start_date', models.DateField()),
                ('expected_completion_date', models.DateField()),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_production_orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='production.product')),
            ],
            options={
                'verbose_name': 'Production Order',
                'verbose_name_plural': 'Production Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('sequence', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('labour_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.labourtask')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='production.productionorder')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Production Task',
                'verbose_name_plural': 'Production Tasks',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.productionorder')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.productiontask')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.workstation')),
            ],
            options={
                'verbose_name': 'Production Line',
                'verbose_name_plural': 'Production Lines',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ProductFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='production.product')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.rawmaterial')),
            ],
            options={
                'verbose_name': 'Product Formula',
                'verbose_name_plural': 'Product Formulas',
                'unique_together': {('product', 'raw_material')},
            },
        ),
    ]
